/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
#define _Included_site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024NormalizedProbabilisticFunction_init
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
 * Method:    Evaluate
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/Matrix;)D
 */
JNIEXPORT jdouble JNICALL Java_site_selyerobotics_jdlib_JDlib_00024NormalizedProbabilisticFunction_Evaluate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
 * Method:    SetNormalizer
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/VectorNormalizer;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024NormalizedProbabilisticFunction_SetNormalizer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
 * Method:    SetFunction
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/DecisionFunction;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024NormalizedProbabilisticFunction_SetFunction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
 * Method:    BasisVectorsSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_site_selyerobotics_jdlib_JDlib_00024NormalizedProbabilisticFunction_BasisVectorsSize
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024NormalizedProbabilisticFunction_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
