/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib */

#ifndef _Included_site_selyerobotics_jdlib_JDlib
#define _Included_site_selyerobotics_jdlib_JDlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    TrainProbabilisticDecisionFunction
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/SVMNuTrainer;Lsite/selyerobotics/jdlib/JDlib/VectorM;Lsite/selyerobotics/jdlib/JDlib/Vectord;J)Lsite/selyerobotics/jdlib/JDlib/DecisionFunction;
 */
JNIEXPORT jobject JNICALL Java_site_selyerobotics_jdlib_JDlib_TrainProbabilisticDecisionFunction
  (JNIEnv *, jclass, jobject, jobject, jobject, jlong);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    Reduced2
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/SVMNuTrainer;JD)Lsite/selyerobotics/jdlib/JDlib/ReducedDecisionFunctionTrainer2;
 */
JNIEXPORT jobject JNICALL Java_site_selyerobotics_jdlib_JDlib_Reduced2
  (JNIEnv *, jclass, jobject, jlong, jdouble);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    RandomizeSamples
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/VectorM;Lsite/selyerobotics/jdlib/JDlib/Vectord;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_RandomizeSamples
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    MaximumNu
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/Vectord;)D
 */
JNIEXPORT jdouble JNICALL Java_site_selyerobotics_jdlib_JDlib_MaximumNu
  (JNIEnv *, jclass, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    CrossValidateTrainer
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/SVMNuTrainer;Lsite/selyerobotics/jdlib/JDlib/VectorM;Lsite/selyerobotics/jdlib/JDlib/Vectord;J)Lsite/selyerobotics/jdlib/JDlib/Matrix;
 */
JNIEXPORT jobject JNICALL Java_site_selyerobotics_jdlib_JDlib_CrossValidateTrainer
  (JNIEnv *, jclass, jobject, jobject, jobject, jlong);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    Serialize
 * Signature: (Ljava/lang/String;Lsite/selyerobotics/jdlib/JDlib/LearnedFunction;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_Serialize__Ljava_lang_String_2Lsite_selyerobotics_jdlib_JDlib_LearnedFunction_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    Serialize
 * Signature: (Ljava/lang/String;Lsite/selyerobotics/jdlib/JDlib/NormalizedProbabilisticFunction;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_Serialize__Ljava_lang_String_2Lsite_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    Deserialize
 * Signature: (Ljava/lang/String;Lsite/selyerobotics/jdlib/JDlib/LearnedFunction;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_Deserialize__Ljava_lang_String_2Lsite_selyerobotics_jdlib_JDlib_LearnedFunction_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib
 * Method:    Deserialize
 * Signature: (Ljava/lang/String;Lsite/selyerobotics/jdlib/JDlib/NormalizedProbabilisticFunction;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_Deserialize__Ljava_lang_String_2Lsite_selyerobotics_jdlib_JDlib_NormalizedProbabilisticFunction_2
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
