/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_Vectord */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_Vectord
#define _Included_site_selyerobotics_jdlib_JDlib_Vectord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_Vectord
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Vectord_init
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Vectord
 * Method:    Add
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Vectord_Add
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Vectord
 * Method:    Size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Vectord_Size
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Vectord
 * Method:    Get
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Vectord_Get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Vectord
 * Method:    Set
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Vectord_Set
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Vectord
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Vectord_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
