/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_VectorM */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_VectorM
#define _Included_site_selyerobotics_jdlib_JDlib_VectorM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorM
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorM_init
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorM
 * Method:    Add
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorM_Add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorM
 * Method:    Size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorM_Size
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorM
 * Method:    Get
 * Signature: (J)Lsite/selyerobotics/jdlib/JDlib/Matrix;
 */
JNIEXPORT jobject JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorM_Get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorM
 * Method:    Set
 * Signature: (JLsite/selyerobotics/jdlib/JDlib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorM_Set
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorM
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorM_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
