/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_DecisionFunction */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_DecisionFunction
#define _Included_site_selyerobotics_jdlib_JDlib_DecisionFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_DecisionFunction
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024DecisionFunction_init
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_DecisionFunction
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024DecisionFunction_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
