/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_ReducedDecisionFunctionTrainer2 */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_ReducedDecisionFunctionTrainer2
#define _Included_site_selyerobotics_jdlib_JDlib_ReducedDecisionFunctionTrainer2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_ReducedDecisionFunctionTrainer2
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024ReducedDecisionFunctionTrainer2_init
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_ReducedDecisionFunctionTrainer2
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024ReducedDecisionFunctionTrainer2_Dispose
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_ReducedDecisionFunctionTrainer2
 * Method:    Train
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/VectorM;Lsite/selyerobotics/jdlib/JDlib/Vectord;)Lsite/selyerobotics/jdlib/JDlib/DecisionFunction;
 */
JNIEXPORT jobject JNICALL Java_site_selyerobotics_jdlib_JDlib_00024ReducedDecisionFunctionTrainer2_Train
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
