/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_Matrix */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_Matrix
#define _Included_site_selyerobotics_jdlib_JDlib_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_Matrix
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Matrix_init__
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Matrix
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Matrix_init__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Matrix
 * Method:    set
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Matrix_set
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Matrix
 * Method:    get
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Matrix_get
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_Matrix
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Matrix_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
