/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_Matrix_Matrix12 */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_Matrix_Matrix12
#define _Included_site_selyerobotics_jdlib_JDlib_Matrix_Matrix12
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_Matrix_Matrix12
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024Matrix_00024Matrix12_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
