/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_VectorNormalizer */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_VectorNormalizer
#define _Included_site_selyerobotics_jdlib_JDlib_VectorNormalizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorNormalizer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorNormalizer_init
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorNormalizer
 * Method:    Train
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/VectorM;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorNormalizer_Train
  (JNIEnv *, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorNormalizer
 * Method:    Normalize
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/Matrix;)Lsite/selyerobotics/jdlib/JDlib/Matrix;
 */
JNIEXPORT jobject JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorNormalizer_Normalize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_VectorNormalizer
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024VectorNormalizer_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
