/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_SVMNuTrainer */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_SVMNuTrainer
#define _Included_site_selyerobotics_jdlib_JDlib_SVMNuTrainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_SVMNuTrainer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024SVMNuTrainer_init
  (JNIEnv *, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_SVMNuTrainer
 * Method:    SetKernel
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/RBF;)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024SVMNuTrainer_SetKernel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_SVMNuTrainer
 * Method:    SetNu
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024SVMNuTrainer_SetNu
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_SVMNuTrainer
 * Method:    Train
 * Signature: (Lsite/selyerobotics/jdlib/JDlib/VectorM;Lsite/selyerobotics/jdlib/JDlib/Vectord;)Lsite/selyerobotics/jdlib/JDlib/DecisionFunction;
 */
JNIEXPORT jobject JNICALL Java_site_selyerobotics_jdlib_JDlib_00024SVMNuTrainer_Train
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_SVMNuTrainer
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024SVMNuTrainer_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
