/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_selyerobotics_jdlib_JDlib_RBF */

#ifndef _Included_site_selyerobotics_jdlib_JDlib_RBF
#define _Included_site_selyerobotics_jdlib_JDlib_RBF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_selyerobotics_jdlib_JDlib_RBF
 * Method:    init
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024RBF_init
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     site_selyerobotics_jdlib_JDlib_RBF
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_selyerobotics_jdlib_JDlib_00024RBF_Dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
